spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/products/**
    loadbalancer:
      cache:
        enabled: false

eureka:
  instance:
    prefer-ip-address: true
