spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/products/**
            - id: notification-consumer
              uri: lb://NOTIFICATION-CONSUMER
              predicates:
                - Path=/notifications/**
    loadbalancer:
      cache:
        enabled: false

eureka:
  instance:
    prefer-ip-address: true

resilience4j:
  ratelimiter:
    instances:
      apiGatewayRateLimiter:
        limit-for-period: 5           # allow 5 requests
        limit-refresh-period: 10s     # per 10 seconds
        timeout-duration: 0s          # don't wait, reject immediately
