server:
  port: 8082

spring:
  application:
    name: notification-service

  config:
    import: optional:configserver:

  cloud:
    config:
      uri: http://localhost:8888

  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
