server:
  port: 8082

spring:
  application:
    name: notification

  config:
    import: optional:configserver:

  cloud:
    config:
      uri: http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
